### ISSUE TITLE
Can't get the PHP files translation working

### ISSUE THREAD

**Issue by bomshteyn** [tanmuhittin/laravel-google-translate#39]
Hi, thanks for this great package!

I have got the JSON translation working, but when i select `PHP` translation the files are not being created.
I tried specifying the file name `validation` that i want to translate but all i get is an empty `validation.php.php` file created containing 
```
return [
];
```

I have the following files inside the base `en` folder: `auth,pagination,validation,passwords` 

If i don't specify any file, so that it translates all the files, the translation does not create the translation files at all.

Any idea what i am doing wrong? 

Versions
- PHP: 7.4
- Laravel: 7.28.4
- laravel-google-translate: 2.0.3

**Comment by tanmuhittin** [comment]
Related to #37 
I am publishing a new release

**Comment by Bojan121** [comment]
@tanmuhittin  Any update about this? When is the new release?

**Comment by bomshteyn** [comment]
@Bojan121 He released this on Nov 13

**Comment by tanmuhittin** [comment]
Its already published https://github.com/tanmuhittin/laravel-google-translate/releases/tag/2.0.4

**Comment by Bojan121** [comment]
Hmm but I'm on 2.0.4 and it's still not working for me, I'm getting exactly the same issue with creating empty array translation files, no error.

PHP: 7.4
Laravel: 7.30.4

If the issue is with the GoogleTranslate API key should I expect an error of some kind? I don't have anything in the logs.

Here is a screenshot on what's happens after running "php artisan translate:files"

<img width="716" alt="Screenshot 2021-01-29 at 16 33 35" src="https://user-images.githubusercontent.com/22980235/106294817-ecd12500-624f-11eb-9e2a-68613b360628.png">

The three new files in lang/de/ contain only empty arrays.
